docs/guide/query_scan.md
samples/guides/src/main/java/app/cash/tempest/guides/java/QueryNScan.java
samples/guides/src/main/kotlin/app/cash/tempest/guides/QueryNScan.kt
tempest/src/main/kotlin/app/cash/tempest/Paging.kt

The Offset constructor was changed to be internal in commit
0ca916f4627a8bc89d2b4b4570c634facfdec0a3, which made it impossible to
query with an arbitrary offset in the table.
One use case for this is to allow an external system to page through the
database, without leaking the details of your schema and access
patterns.

Expose Offset constructor

---

tempest/src/main/kotlin/app/cash/tempest/internal/DynamoDbLogicalDb.kt
tempest/src/test/kotlin/app/cash/tempest/CodecTest.kt
tempest/src/test/kotlin/app/cash/tempest/LogicalDbTransactionTest.kt

Wrapping in IllegalStateException leads to upstream callers returning
500s but many of these exceptions are concurrency and Dynamo resource
contention related and should return 503s. Sending the raw
TransactionCanceledException is more transparent and manageable for
upstream callers.

Remove IllegalStateException wrapping of TransactionCanceledException

---

samples/musiclibrary/src/main/kotlin/app/cash/tempest/reservedwords/ReservedWordsDb.kt
samples/musiclibrary/src/main/kotlin/app/cash/tempest/reservedwords/ReservedWordsItem.kt
samples/musiclibrary/src/main/kotlin/app/cash/tempest/reservedwords/ReservedWordsTable.kt
tempest/src/main/kotlin/app/cash/tempest/internal/DynamoDbQueryable.kt
tempest/src/test/kotlin/app/cash/tempest/DynamoDbQueryableTest.kt
tempest/src/test/kotlin/app/cash/tempest/musiclibrary/MusicDbTestModule.kt

This will replace reserved words with specified aliases, and add a mapping from aliases to reserved words as the `expressionAttributeNames` parameter. Mostly wrote this based off of this doc: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.ExpressionAttributeNames.html and the `DynamoDBQueryExpression` class.
Still needs to have the rest of the reserved words added if this seems like a reasonable approach.

Automatically handle reserved words

---

tempest/src/main/kotlin/app/cash/tempest/Model.kt
tempest/src/main/kotlin/app/cash/tempest/internal/DynamoDbLogicalDb.kt
tempest/src/test/kotlin/app/cash/tempest/LogicalDbTransactionTest.kt
tempest2/src/main/kotlin/app/cash/tempest2/Model.kt
tempest2/src/main/kotlin/app/cash/tempest2/internal/DynamoDbLogicalDb.kt
tempest2/src/test/kotlin/app/cash/tempest2/LogicalDbTransactionTest.kt

Instead of printing the full item, which might contain sensitive information, only print the item key.

Omit non-key attributes from transaction cancellation exceptions

---

tempest/src/main/kotlin/app/cash/tempest/LogicalDb.kt
tempest2/src/main/kotlin/app/cash/tempest2/LogicalDb.kt

Closes #41
See https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/dynamodbv2/datamodeling/DynamoDBMapper.html#transactionWrite-com.amazonaws.services.dynamodbv2.datamodeling.TransactionWriteRequest-com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapperConfig-

Improve documentation

---

tempest2/src/main/kotlin/app/cash/tempest2/internal/AsyncLogicalDbFactory.kt
tempest2/src/main/kotlin/app/cash/tempest2/internal/DynamoDbLogicalDb.kt
tempest2/src/main/kotlin/app/cash/tempest2/internal/LogicalDbFactory.kt
tempest2/src/main/kotlin/app/cash/tempest2/internal/TableSchemaFactory.kt
tempest2/src/main/kotlin/app/cash/tempest2/internal/V2.kt

This improves the performance of `tempest2`. 
In batch and transactional operations, tempest2 creates a `TableSchema` for each item it processes. Profiling has showed that `TableSchema.fromClass` is an expensive operation and this has caused excess allocation and GC pauses. This PR caches the results in memory.

Cache reflection results

---

build.gradle.kts
buildSrc/src/main/kotlin/Dependencies.kt

This helps with publishing the internal square snapshot
release.

Upgrade spotless to a 5.x version

---

buildSrc/src/main/kotlin/Dependencies.kt

This provides better security against the RCE vuln that was
partially fixed in 2.15.0.

Update log4j version to 2.16.0.

---

README.md
docs/guide/v2_upgrade_guide.md

After recently upgrading a service from Tempest 1 to Tempest 2 I put together a quick document on all the migration changes we needed.

Create Migration guide from v1 to v2

---

build.gradle.kts
tempest2/src/main/kotlin/app/cash/tempest2/Model.kt
tempest2/src/main/kotlin/app/cash/tempest2/WritingPager.kt
tempest2/src/test/kotlin/app/cash/tempest2/WritingPagerTest.kt

This adds a hook point for just after a page is written. (Somewhat confusingly, the existing `finishPage` method is invoked just prior to actually writing the page).
My immediate use case here is for capturing the time delta between initiating page computation and return from a successful write, but this also seems generically useful.

Adds a pageWritten WritingPager.Handler method

---

.github/workflows/Release.yml

Followup to #132, this isn't needed with the
hermitized JDK.

Remove java setup action

---

tempest2-testing-internal/src/main/kotlin/app/cash/tempest2/testing/internal/DefaultTestDynamoDbClient.kt
tempest2-testing-internal/src/main/kotlin/app/cash/tempest2/testing/internal/TestUtils.kt

Additionally for DefaultTestDynamoDbClient only perform the hostname determination introduced in https://github.com/cashapp/tempest/pull/97 once.

Use a shorter timeout when connecting to test dynamo server

---

CHANGELOG.md
README.md
gradle.properties
mkdocs.yml
samples/musiclibrary-testing/src/main/kotlin/app/cash/tempest/musiclibrary/TestEntities.kt
samples/musiclibrary2/src/main/kotlin/app/cash/tempest2/musiclibrary/MusicItem.kt
samples/musiclibrary2/src/main/kotlin/app/cash/tempest2/musiclibrary/MusicTable.kt
tempest-internal/src/main/kotlin/app/cash/tempest/internal/Annotation.kt
tempest-internal/src/main/kotlin/app/cash/tempest/internal/Codec.kt
tempest-internal/src/main/kotlin/app/cash/tempest/internal/Schema.kt
tempest/src/main/kotlin/app/cash/tempest/internal/V1.kt
tempest2/src/main/kotlin/app/cash/tempest2/Annotation.kt
tempest2/src/main/kotlin/app/cash/tempest2/internal/V2.kt
tempest2/src/test/kotlin/app/cash/tempest2/DynamoDbQueryableTest.kt
tempest2/src/test/kotlin/app/cash/tempest2/internal/SchemaTest.kt
tempest2/src/test/kotlin/app/cash/tempest2/musiclibrary/TestUtils.kt

Currently Tempest will add an `Attribute.prefix` to a field even if it is nullable and `null`. This causes two issues
1. [removePrefix](https://github.com/cashapp/tempest/blob/96fc15ebeb0684a8fcaa44b1fb731fcf983fdb71/tempest-internal/src/main/kotlin/app/cash/tempest/internal/Codec.kt#L136) fails with a nullable value
2. Sparse GSIs cannot be used, since the value will always include the `prefix`
Since it is possible that existing users are relying on the `prefix` being added to null fields changing this behavior would be a breaking change, as the field would stop being written.
This PR introduces a new `Attribute.allowEmpty` flag that defaults to `false`. When it is `true` and the field is set to `null` it will not have the `prefix` added, and checks against the field (such as query …

feat: support sparse, prefixed GSIs with Attribute.allowEmpty

---

buildSrc/src/main/kotlin/Dependencies.kt

Gets a fix for SNAPSHOT builds [0.25.1](https://github.com/vanniktech/gradle-maven-publish-plugin/pull/545)

fix: bump vanniktech

---

.github/workflows/Release.yml
build.gradle.kts

per guidance
```
In general publishing dependencies to enforced platforms is a mistake: enforced platforms shouldn't be used for published components because they behave like forced dependencies and leak to consumers. This can result in hard to diagnose dependency resolution errors. If you did this intentionally you can disable this check by adding 'enforced-platform' to the suppressed validations of the :tempest-internal:generateMetadataFileForMavenPublication task
```
Setting this as un-enforced caused another error
```
> No matching variant of project :tempest-bom was found. The consumer was configured to find an API of a library compatible with Java 8, preferably in the form of class files, preferably optimized for standard JVMs, and its dependencies declared externally, as well as …
```

Remove enforcedPlatform

---

README.md
docs/guide/getting_started.md

A used reported an issue where an `Offset` that contained a default value was breaking querying, since the value was included in the `initialOffset` value during paging. While the current docs make some allusions to the base type being nullable, they never state this is a requirement. This note should address that.

docs: add a note explaining the need for an empty base type

---

CHANGELOG.md
gradle.properties

This reverts commit 996c49fa1b9902687827a8b4cdec18cbfc91f8e0.
Releasing is too complicated with tags and forks, just going to revert since pretty sure nothing happened.

Revert "Prepare for release 1.10.1 (#158)"

---

tempest2/src/main/kotlin/app/cash/tempest2/internal/DynamoDbLogicalDb.kt

The `toTransactionWriteException` function in `DynamoDbLogicalDb` class intends to decorate the exception with a meaningful `message` without wrapping the AWS exception, but in this process completely creates the exception instance from scratch. We can create the exception instance with the builder by using `toBuilder()` function which would use the current state of the exception.

Improve handling of TransactionCanceledException by avoid creating new instance of it from scratch

---

gradle/libs.versions.toml
tempest2/src/main/kotlin/app/cash/tempest2/AsyncLogicalDb.kt
tempest2/src/main/kotlin/app/cash/tempest2/AsyncQuery.kt
tempest2/src/main/kotlin/app/cash/tempest2/AsyncView.kt
tempest2/src/main/kotlin/app/cash/tempest2/LogicalDb.kt
tempest2/src/main/kotlin/app/cash/tempest2/Model.kt
tempest2/src/main/kotlin/app/cash/tempest2/Paging.kt
tempest2/src/main/kotlin/app/cash/tempest2/Query.kt
tempest2/src/main/kotlin/app/cash/tempest2/View.kt
tempest2/src/main/kotlin/app/cash/tempest2/internal/DynamoDbLogicalDb.kt
tempest2/src/main/kotlin/app/cash/tempest2/internal/DynamoDbQueryable.kt
tempest2/src/main/kotlin/app/cash/tempest2/internal/DynamoDbScannable.kt
tempest2/src/main/kotlin/app/cash/tempest2/internal/DynamoDbView.kt
tempest2/src/main/kotlin/app/cash/tempest2/internal/UnsupportedAsyncQueryable.kt
tempest2/src/main/kotlin/app/cash/tempest2/internal/UnsupportedQueryable.kt
tempest2/src/test/kotlin/app/cash/tempest2/DynamoDbAsyncQueryableTest.kt
tempest2/src/test/kotlin/app/cash/tempest2/DynamoDbAsyncViewTest.kt
tempest2/src/test/kotlin/app/cash/tempest2/DynamoDbQueryableTest.kt
tempest2/src/test/kotlin/app/cash/tempest2/DynamoDbViewTest.kt
tempest2/src/test/kotlin/app/cash/tempest2/LogicalDbBatchTest.kt

This was not possible with the old version of the enhanced client and was recently added. This will allow us to optionally get data on the consumed capacity for each of these calls and make informed decisions on design viability.

Add APIs to execute batch, query and load requests along with consumed capacity

---

buildSrc/build.gradle.kts
gradle/libs.versions.toml

Hi team! I'm back again. Sorry for breaking main with my last bump.
It seems like 1.8.22 isn't high enough to resolve the version conflict. I tried bumping the version to the latest published tempest version and still ran into the same issues.
Here's another bump of kotlin to 1.9.23, along with a version bump to unbreak the publishing job.
Running `./bin/gradle clean publishToMavenLocal --stacktrace` locally failed before the dokka bump, and passed afterwards.

Bump to kotlin 1.9.23, Dokka 1.9.20

---

samples/musiclibrary2/src/main/kotlin/app/cash/tempest2/musiclibrary/MusicItem.kt
samples/musiclibrary2/src/main/kotlin/app/cash/tempest2/musiclibrary/MusicTable.kt
tempest2/src/main/kotlin/app/cash/tempest2/internal/DynamoDbLogicalDb.kt
tempest2/src/test/kotlin/app/cash/tempest2/AsyncLogicalDbBatchTest.kt
tempest2/src/test/kotlin/app/cash/tempest2/LogicalDbBatchTest.kt
tempest2/src/test/kotlin/app/cash/tempest2/WritingPagerTest.kt
tempest2/src/test/kotlin/app/cash/tempest2/internal/SchemaTest.kt

This fixes a somewhat subtle bug I realized `tempest2` has.
From the [enhanced client docs](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/enhanced/dynamodb/DynamoDbEnhancedClient.html#batchGetItem(software.amazon.awssdk.enhanced.dynamodb.model.BatchGetItemEnhancedRequest)) (emphasis mine): 
> Partial results. A single call to DynamoDb has restraints on how much data can be retrieved. If those limits are exceeded, the call yields a partial result. This may also be the case if provisional throughput is exceeded or there is an internal DynamoDb processing failure. The operation automatically retries any unprocessed keys returned from DynamoDb **in subsequent calls for pages**.
Tempest currently only gets the first page of results.
From the …

bugfix: Consume all result pages in DynamoDbLogicalDb.batchLoad

---

tempest2-testing/src/main/kotlin/app/cash/tempest2/testing/TestDynamoDbClient.kt
tempest2/src/main/kotlin/app/cash/tempest2/AsyncLogicalDb.kt
tempest2/src/main/kotlin/app/cash/tempest2/LogicalDb.kt
tempest2/src/main/kotlin/app/cash/tempest2/TableNameResolver.kt
tempest2/src/main/kotlin/app/cash/tempest2/internal/AsyncLogicalDbFactory.kt
tempest2/src/main/kotlin/app/cash/tempest2/internal/LogicalDbFactory.kt
tempest2/src/main/kotlin/app/cash/tempest2/internal/V2.kt
tempest2/src/test/kotlin/app/cash/tempest2/DynamoDbAsyncTableNameResolverTest.kt
tempest2/src/test/kotlin/app/cash/tempest2/DynamoDbTableNameResolverTest.kt
tempest2/src/test/kotlin/app/cash/tempest2/musiclibrary/TestUtils.kt

I'm running into a limitation of `tempest2` - static table names. This is a limitation that `tempest` doesn't have, because it allows callers to pass in a `DynamoDbMapperConfig` that includes either an override or a table name resolver ([relevant javadoc](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/dynamodbv2/datamodeling/DynamoDBMapperConfig.Builder.html#withTableNameOverride-com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapperConfig.TableNameOverride-))
The AWS v2 client library doesn't support a way of resolving/overriding table names. I think this is because the enhanced client allows you to pass in the table name as a string, removing the need for the v2 client to care about how the name gets resolved. Unfortunately `tempest2` uses AWS …

Add TableNameResolver to tempest2

---

tempest-testing-internal/src/main/kotlin/app/cash/tempest/testing/internal/TestUtils.kt
tempest2-testing-docker/src/main/kotlin/app/cash/tempest2/testing/DockerDynamoDbServer.kt
tempest2-testing-internal/src/main/kotlin/app/cash/tempest2/testing/internal/TestDynamoDbService.kt
tempest2-testing-internal/src/main/kotlin/app/cash/tempest2/testing/internal/TestUtils.kt
tempest2-testing-jvm/src/main/kotlin/app/cash/tempest2/testing/JvmDynamoDbServer.kt
tempest2-testing/src/main/kotlin/app/cash/tempest2/testing/TestDynamoDbServer.kt

Follow-up from https://github.com/cashapp/tempest/pull/182

Tempest2 - Hold onto allocated ports to avoid port conflicts in concurrent tests

---

tempest-testing-internal/src/main/kotlin/app/cash/tempest/testing/internal/TestDynamoDbService.kt
tempest-testing-internal/src/main/kotlin/app/cash/tempest/testing/internal/TestUtils.kt
tempest2-testing-internal/src/main/kotlin/app/cash/tempest2/testing/internal/TestDynamoDbService.kt
tempest2-testing-internal/src/main/kotlin/app/cash/tempest2/testing/internal/TestUtils.kt

Follow-up from https://github.com/cashapp/tempest/pull/184 and https://github.com/cashapp/tempest/pull/182
The previous implementation fails with a port already bound error, if a first test creates a test dynamodb server, but doesn't start and then a second test tries to start the server, because the socket allocated in the first test and reused in the second test doesn't get closed (due to first test not calling `startUp`). 
This PR makes it so that we close the socket if it's not closed even when it's reused across tests.

Try to close reused sockets in TestDynamoDbService

---

tempest2/src/main/kotlin/app/cash/tempest2/internal/DynamoDbLogicalDb.kt
tempest2/src/test/kotlin/app/cash/tempest2/LogicalDbFailueTest.kt
tempest2/src/test/kotlin/app/cash/tempest2/LogicalDbFailureTest.kt

I started running into exceptions that looked like the following:
```
java.lang.IllegalArgumentException: Cannot find a dynamodb table for class software.amazon.awssdk.enhanced.dynamodb.Key
at app.cash.tempest2.internal.DynamoDbLogicalDb.expectedRawItemType(DynamoDbLogicalDb.kt:390)
at app.cash.tempest2.internal.DynamoDbLogicalDb.rawItemKey(DynamoDbLogicalDb.kt:376)
at app.cash.tempest2.internal.DynamoDbLogicalDb.toBatchWriteResponse(DynamoDbLogicalDb.kt:308)
at app.cash.tempest2.internal.DynamoDbLogicalDb.access$toBatchWriteResponse(DynamoDbLogicalDb.kt:65)
at app.cash.tempest2.internal.DynamoDbLogicalDb$Sync.batchWrite(DynamoDbLogicalDb.kt:120)
at app.cash.tempest2.LogicalDb.batchWrite(LogicalDb.kt:125)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandl …
```

Handle unprocessed deletes without throwing an IllegalArgumentException

---

tempest-testing-docker/src/main/kotlin/app/cash/tempest/testing/Containers.kt
tempest2-testing-docker/src/main/kotlin/app/cash/tempest2/testing/Containers.kt

We've encountered some test failures where tempest can't remove the Docker network. I'm not sure why this happens, but it shouldn't cause the test to failure. Instead we should just log a message, just like we do when we fail to remove a container.

Handle network removal gracefully

---

tempest2/src/main/kotlin/app/cash/tempest2/LogicalDb.kt
tempest2/src/test/kotlin/app/cash/tempest2/LogicalDbBatchTest.kt

Currently this is not respecting the `consistentReads` parameter. This PR fixes that by removing the hard-coded value.

pass consistentReads through overload

---

tempest-testing-jvm/build.gradle.kts
tempest2-testing-jvm/build.gradle.kts

This should allow downstream consumers of tempest to automatically pick up the correct libsqlite version without having to duplicate this dependency into their own builds.

Make the aarch64 lib dependency unconditional

---

gradle/libs.versions.toml
tempest-testing-jvm/build.gradle.kts
tempest-testing-jvm/src/main/kotlin/app/cash/tempest/testing/JvmDynamoDbServer.kt
tempest2-testing-jvm/build.gradle.kts
tempest2-testing-jvm/src/main/kotlin/app/cash/tempest2/testing/JvmDynamoDbServer.kt

This adds support for linux/arm64 and removes the use of the unmaintained sqlite4java

Upgrade AWS DynamoDB Local to v2.6.0

---

build.gradle.kts
gradle/libs.versions.toml
tempest-dynamodb-local/build.gradle.kts

By default, the gradle module metadata points at the unshaded jar and dependencies. Modify the resulting JSON to instead use the dependencies from the shadow jar for the `runtimeElements` variant
Note that while gradle has an API for modifying variants (i.e. `AdhocComponentWithVariants`), it does not provide an ergonomic means for modifying the dependencies, so use post-processing similar to what we already do for the POM file

Post-process the grade module metadata to use the shadow jar deps

---

build.gradle.kts
gradle/libs.versions.toml
tempest-dynamodb-local/build.gradle.kts

Gradle wants `formatVersion` to come first, so switch to a json parser does the right thing

Switch from org.jsom to jackson to preserve property ordering

---

tempest-dynamodb-local/build.gradle.kts

This fixes the following error when there are ANTLR version mismatches:
```
org.antlr.v4.runtime.atn.ATN; Could not deserialize ATN with version 4 (expected 3)
```

Shade ANTLR in tempest-dynamodb-local

---

tempest-dynamodb-local/build.gradle.kts
tempest-testing-jvm/build.gradle.kts
tempest2-testing-jvm/build.gradle.kts

https://cash.slack.com/archives/C01G7QB4ANQ/p1746050279119679
Relates to these PRs:
1. https://github.com/cashapp/tempest/pull/225/files
2. https://github.com/cashapp/tempest/pull/226/files
3. https://github.com/cashapp/tempest/pull/228/files
To check this against the current state, one could do the following:
```
mkdir -p /tmp/shadowed
git checkout main
gradle t-d-l:pTML
cp -r ~/.m2/repository/app/cash/tempest/tempest-dynamodb-local/0.0-SNAPSHOT/ /tmp/shadowed/a
git checkout <this PR>
gradle t-d-l:pTML
cp -r ~/.m2/repository/app/cash/tempest/tempest-dynamodb-local/0.0-SNAPSHOT/ /tmp/shadowed/b
diff --brief --recursive /tmp/shadowed/a /tmp/shadowed/b
```
There will be some differences, but they should not result in any semantic difference.

chore: simplify shadowJar publishing.
